replicaCount: 2

image: lkuzmicheva/crud-service

service:
  type: ClusterIP
  port: 9000
  targetPort: web

ingress:
  enabled: true
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
  hosts:
  - host: arch.homework
    paths: ["/otusapp/kuzmicheva(/|$)(.*)"]

cassandra:
  enabled: true
  service:
    port: 9042
  dbUser:
    user: cassandra
    password: cassandra
  cluster:
    datacenter: dc1
  initDBConfigMap: init-db
  contactPoints: crud-service-cassandra

appCassandra:
  user: crud_service
  password: crud_service
