apiVersion: v1
kind: ConfigMap
metadata:
  name: init-db
data:
  initdb.cql: |
    create keyspace if not exists crud_service with replication = { 'class' : 'SimpleStrategy', 'replication_factor' : 1 };
    create user crud_service with password 'crud_service' nosuperuser;
    grant all permissions on keyspace crud_service to crud_service;
    create table if not exists crud_service.user(name text, email text, primary key (name));
    insert into crud_service.user(name, email) values ('test', 'mail@mail.ru');
  